/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package processamento.paralelo

class App {

    static void main(String[] args) {
        println("Quantos fatoriais você quer?")
        Scanner scanner = new Scanner(System.in)
        int tam = scanner.nextInt()

        println("Digite ${tam} números inteiros:")
        int[] vetor = new int[tam]

        for (int i = 0; i < tam; i++) {
            println("Digite vetor[${i}]:")
            vetor[i] = scanner.nextInt()
        }

        BigDecimal[] fat = new BigDecimal[tam]

        for (int i = 0; i < tam; i++) {
            fat[i] = 1

            for (int j = 2; j <= vetor[i]; j++) {
                fat[i] = (fat[i] * j).toBigDecimal()
            }
        }

        for (int i = 0; i < tam; i++) {
            println("Fatorial de ${vetor[i]} = ${fat[i].toString()}")
        }

    }
}
